version: '3'

services: 
       redisserver:
               image: redis
               ports:
                  - "6379:6379"
       redisclient:
               restart: always
               image: joydeep56053/redis-client
               volumes:
                       - /root/docker:/var
